### ISSUE TITLE
整合乐观更新？

### ISSUE THREAD

**Issue by Amorites** [ecomfe/standard-redux-shape#6]
把乐观更新的能力整合进来的话，可以少些很多业务代码。有一点初步的想法，可能会有不太妥当的地方，仅供参考：

## 场景

增删改（POST, DELETE, PUT, PATCH）

## API 设计

1. 在`thunkCreatorFor`里面加一项 option，需要用户输入的信息有：

- 是否开启乐观更新
- POST专用：我们不知道新的 id 在数组里应该处在什么位置，可行的做法：用户可以选择最前、最后、或一个用来排序的函数

2. 四个（POST, DELETE, PUT, PATCH）类似 `acceptLatest` 可以把 actions 包起来的高阶函数，根据 action 建立有默认行为的 reducer。再使用 `compose`将（GET, POST, DELETE）连起来，共同处理一个 query。

## 实现

- 初步看了下`redux-optimistic-manager`的文档，感觉上`createOptimisticManager`的返回值应该传给 `thunkCreatorFor` 使用，但没想好怎么传。
- 增删需要修改 query 里的 id 列表，因此需要知道当前的筛选条件。
- 四个 reducer creator 提供默认 reducer 行为的同时，调用 `createOptimisticReducer`。

**Comment by otakustay** [comment]
我猜只要给`createThunkFor`加一个`optimisticResponse: params => response`的配置就行了

> 增删需要修改 query 里的 id 列表，因此需要知道当前的筛选条件。

这个事情是不应该的……我和宇轩有说过一次，后续单独给大家都做一些讲解吧- -

**Comment by otakustay** [comment]
`createOptimisticReducer`是一个全局的东西，在store的级别生效就行，因此也不需要这个库来支持

**Comment by otakustay** [comment]
又想了一下，甚至不需要做任何事情，直接dispatch的地方丢数组，数组第一项是thunkCreatorFor搞出来的就好了啊

**Comment by Amorites** [comment]
> 又想了一下，甚至不需要做任何事情，直接dispatch的地方丢数组，数组第一项是thunkCreatorFor搞出来的就好了啊

是让用户自己配置好`redux-optimistic-thunk`吗？

> createOptimisticReducer是一个全局的东西，在store的级别生效就行，因此也不需要这个库来支持

我之前是觉得一个功能需要两个库一起用有点麻烦（不利于推广），最好是能在一个库里全都解决。

**Comment by otakustay** [comment]
lib和solution是两个层面的东西，我们可以把东西都整合起来做一个新的solution级别的包，但不需要因此让下面的任何一个独立的lib去相互依赖

唯一的难点是，整个的包叫啥名字……
